use_frameworks!

platform :ios, '10.0'

target 'ChachisBeta_Example' do
  pod 'ChachisBeta'#, :path => '../'
  pod 'MLUI', :git => 'git@github.com:carloschaguendoml/MLUI.git', :branch => 'develop'

  target 'ChachisBeta_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
